# Generated by Django 4.1.3 on 2023-09-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='likepost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('post_id', models.CharField(max_length=100)),
            ],
        ),
    ]
